server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: prod
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: "*"
            allowedCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: pin-service
          uri: lb://pin-service
          predicates:
            - Path=/pin/**
          filters:
              - StripPrefix=1
              - AuthenticationFilter

jwt:
  secret: secret12345