#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/app_db
#    username: docker
#    password: docker

spring:
  datasource:
    url: jdbc:h2:mem:dev_db;MODE=MySQL
    username: dev
    password: dev
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true