server:
  port: 8081

spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:application_db
    username: dev
    password: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

