server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: prod
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: secret12345