server:
  port: 8081

spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/users_db
    username: docker
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

