server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      # Auth Service
#      - id: auth-service
#        uri: lb://auth-service
#        predicates:
#        - Path=/auth-api/**
#        # User Service
#      - id: user-service
#        uri: lb://user-service
#        predicates:
#        - Path=/user-api/**
#        filters:
#        - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: secret12345