server:
  port: 8082

spring:
  application:
    name: pin-service
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations:
      - classpath:db/migration