services:

  eureka-server:
    build:
      context: ../backend/modules/eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  auth-service:
    build:
      context: ../backend/modules/auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
     - eureka-server

  pin-service:
    build:
      context: ../backend/modules/pin-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  api-gateway:
    build:
      context: ../backend/modules/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - auth-service
      - pin-service