services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=users_db
    ports:
      - '3306:3306'
